# Generated by Django 5.1.15 on 2026-05-19 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'order_timeline',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order_type', models.CharField(choices=[('ONLINE_PAYMENT', 'Online Challan Payment'), ('COURT_SETTLEMENT', 'Court Settlement Service')], max_length=32)),
                ('order_status', models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_SUCCESS', 'Payment Success'), ('UNDER_REVIEW', 'Under Review'), ('COURT_PROCESSING', 'Court Processing'), ('SETTLEMENT_IN_PROGRESS', 'Settlement In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=32)),
                ('payment_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=32)),
                ('settlement_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_APPLICABLE', max_length=32)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('convenience_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_status', models.CharField(choices=[('NONE', 'None'), ('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NONE', max_length=32)),
                ('refund_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='challans.challandetail')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
