# Generated by Django 5.1.15 on 2026-05-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_checkout_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
