# Generated by Django 5.1.15 on 2026-05-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
