# Generated by Django 5.1.15 on 2026-05-19 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_number', models.CharField(db_index=True, max_length=12)),
                ('vehicle_type', models.CharField(choices=[('private', 'Private'), ('commercial', 'Commercial')], default='private', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
                'indexes': [models.Index(fields=['vehicle_number'], name='vehicles_vehicle_07aa58_idx'), models.Index(fields=['user', 'vehicle_number'], name='vehicles_user_id_e240e0_idx')],
                'unique_together': {('user', 'vehicle_number')},
            },
        ),
    ]
