# Generated by Django 5.1.15 on 2026-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='external_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='external_subscriber_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='external_vehicle_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
