# Generated by Django 5.1.15 on 2026-05-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_challanpay_external_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='display_label',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_searched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
