# Generated by Django 5.1.15 on 2026-05-19 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driveclear_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otpauditlog',
            index=models.Index(fields=['phone_number', 'created_at'], name='otp_audit_l_phone_n_c3152c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['user', 'device_id'], name='device_sess_user_id_738395_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['last_seen_at'], name='device_sess_last_se_c6d391_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicesession',
            unique_together={('user', 'device_id')},
        ),
    ]
