# Generated by Django 5.1.15 on 2026-05-19 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challans', '0003_fulfilment_and_vehicle_search'),
        ('orders', '0003_checkout_batch_id'),
        ('vehicles', '0003_fulfilment_and_vehicle_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallanFulfilment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_number', models.CharField(db_index=True, max_length=12)),
                ('challan_number', models.CharField(db_index=True, max_length=64)),
                ('order_type', models.CharField(choices=[('ONLINE_PAYMENT', 'Online Challan Payment'), ('COURT_SETTLEMENT', 'Court Settlement Service')], max_length=32)),
                ('challan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fulfilment_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=32)),
                ('refund_status', models.CharField(choices=[('NONE', 'None'), ('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='NONE', max_length=32)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('razorpay_refund_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('refund_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('refund_completed_at', models.DateTimeField(blank=True, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('checkout_batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('settlement_reference', models.CharField(blank=True, max_length=128)),
                ('failure_reason', models.TextField(blank=True)),
                ('ops_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('challan', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='fulfilments', to='challans.challandetail')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='fulfilments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challan_fulfilments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilments', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'challan_fulfilment',
                'indexes': [models.Index(fields=['user', 'fulfilment_status'], name='challan_ful_user_id_e72ecf_idx'), models.Index(fields=['vehicle_number', 'created_at'], name='challan_ful_vehicle_4e3890_idx'), models.Index(fields=['challan_number'], name='challan_ful_challan_b741ee_idx'), models.Index(fields=['checkout_batch_id'], name='challan_ful_checkou_bd3fa6_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_id',), name='uniq_fulfilment_per_order')],
            },
        ),
    ]
