# Generated by Django 5.1.15 on 2026-05-19 17:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('challan_number', models.CharField(db_index=True, max_length=64)),
                ('vehicle_number', models.CharField(db_index=True, max_length=12)),
                ('challan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('challan_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed'), ('SETTLED', 'Settled'), ('UNKNOWN', 'Unknown')], default='PENDING', max_length=32)),
                ('challan_type', models.CharField(blank=True, max_length=64)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('source_name', models.CharField(default='challanpay', max_length=64)),
                ('source_response', models.JSONField(blank=True, default=dict)),
                ('normalized_response', models.JSONField(blank=True, default=dict)),
                ('payment_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=32)),
                ('settlement_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_APPLICABLE', max_length=32)),
                ('is_court_challan', models.BooleanField(default=False)),
                ('raw_api_response', models.JSONField(blank=True, default=dict)),
                ('api_request_payload', models.JSONField(blank=True, default=dict)),
                ('state_name', models.CharField(blank=True, max_length=64)),
                ('city_name', models.CharField(blank=True, max_length=64)),
                ('offence_details', models.JSONField(blank=True, default=list)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'challan_details',
            },
        ),
        migrations.CreateModel(
            name='ChallanFetchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_number', models.CharField(db_index=True, max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('api_request_payload', models.JSONField(default=dict)),
                ('raw_api_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'db_table': 'challan_fetch_requests',
            },
        ),
    ]
