# Generated by Django 5.1.15 on 2026-05-19 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challans', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challandetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challandetail',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challans', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='challanfetchrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challanfetchrequest',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='challandetail',
            name='fetch_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challans.challanfetchrequest'),
        ),
        migrations.AddIndex(
            model_name='challanfetchrequest',
            index=models.Index(fields=['user', 'created_at'], name='challan_fet_user_id_69a10a_idx'),
        ),
        migrations.AddIndex(
            model_name='challanfetchrequest',
            index=models.Index(fields=['vehicle_number', 'created_at'], name='challan_fet_vehicle_66134c_idx'),
        ),
        migrations.AddIndex(
            model_name='challanfetchrequest',
            index=models.Index(fields=['status'], name='challan_fet_status_c126a4_idx'),
        ),
        migrations.AddIndex(
            model_name='challandetail',
            index=models.Index(fields=['user', 'vehicle_number'], name='challan_det_user_id_e76117_idx'),
        ),
        migrations.AddIndex(
            model_name='challandetail',
            index=models.Index(fields=['challan_number'], name='challan_det_challan_b68efd_idx'),
        ),
        migrations.AddIndex(
            model_name='challandetail',
            index=models.Index(fields=['payment_status'], name='challan_det_payment_6fadbf_idx'),
        ),
        migrations.AddIndex(
            model_name='challandetail',
            index=models.Index(fields=['fetched_at'], name='challan_det_fetched_37de3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='challandetail',
            constraint=models.UniqueConstraint(fields=('user', 'challan_number', 'vehicle_number'), name='uniq_user_challan_vehicle'),
        ),
    ]
