# Generated by Django 5.1.15 on 2026-05-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challandetail',
            name='challan_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPS_PENDING', 'Operations Pending'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed'), ('SETTLED', 'Settled'), ('UNKNOWN', 'Unknown')], default='PENDING', max_length=32),
        ),
    ]
